/* --------------------------------------------------
   Copyright (C): OpenGATE Collaboration
   This software is distributed under the terms
   of the GNU Lesser General  Public Licence (LGPL)
   See LICENSE.md for further details
   -------------------------------------------------- */

#ifndef GateDigitizerOpticalGenerativeActor_h
#define GateDigitizerOpticalGenerativeActor_h

#include "../GateUniqueVolumeID.h"
#include "GateVDigitizerWithOutputActor.h"
#include <G4Cache.hh>
#include <pybind11/functional.h>
#include <pybind11/stl.h>

namespace py = pybind11;

/* For every energy-deposition step, the actor samples N from a Poisson distribution
   (N = Poisson(edep *scintillation_yield)) and calls a generative model once per hit with the
   batch size being N. The model generates N synthetic particles (e.g. optical photons) records
   in one call.
   
   The precise quantities that are generated can be declared in the bundle manifest which caries
   additional information about the generative model used.
*/


class GateDigitizerOpticalGenerativeActor : public GateVDigitizerWithOutputActor {

public:
  // Callback called once per hit; reads fInputX/Y/Z/Time/N and fills
  // fOutputColumns with one vector per model column, all of the same length.
  using GeneratorType =
      std::function<void(GateDigitizerOpticalGenerativeActor *)>;

  explicit GateDigitizerOpticalGenerativeActor(py::dict &user_info);

  ~GateDigitizerOpticalGenerativeActor() override;

  void InitializeUserInfo(py::dict &user_info) override;

  void StartSimulationAction() override;

  void EndOfEventAction(const G4Event *event) override;

  void SetGeneratorFunction(GeneratorType &f);

  // scintillation yield in photons/MeV; N ~ Poisson(edep * yield)
  double fScintillationYield;

  // input to the generator (set once per hit before calling fGenerator)
  double fInputX, fInputY, fInputZ;
  double fInputTime;
  long fInputN;  // number of photons generated by this hit

  // output from the generator: one vector per model column, in the order the
  // declared outputs list them (constant slots excluded). All columns share
  // one length, which may be smaller than fInputN
  std::vector<std::vector<double>> fOutputColumns;

protected:
  void DigitInitialize(
      const std::vector<std::string> &attributes_not_in_filler) override;

  GeneratorType fGenerator;

  // The declared output schema, one entry per slot, filled from user_info.
  // A slot is either a model column (fOutputColumnIndices >= 0, indexing into
  // fOutputColumns) or a constant (index < 0, value in fOutputConstants).
  std::vector<std::string> fOutputAttributeNames;
  std::vector<std::string> fOutputComponents;  // "x", "y", "z" or "" (scalar)
  std::vector<int> fOutputColumnIndices;
  std::vector<double> fOutputConstants;
  // 1 = value is a delay relative to the hit's GlobalTime, 0 = absolute
  std::vector<int> fOutputRelativeToHit;
  // 0=ordinary slot, 1=module-local position transformed back into the world
  // frame, 2=copied from the hit that produced the photon
  static constexpr int fDerivedNone = 0;
  static constexpr int fDerivedWorldFromModule = 1;
  static constexpr int fDerivedFromHit = 2;
  std::vector<int> fOutputDerived;

  // number of columns the generator must return (slots that are not constants)
  int fNumberOfModelColumns{0};

  // whether the input's PreStepUniqueVolumeID has to be tracked: to invert the
  // module-local transform, to copy it onto every photon, or both
  bool fNeedsVolumeID{false};

  // the attributes declared "from_hit", in the order they were declared
  std::vector<std::string> fFromHitAttributeNames;

  // One target per distinct attribute, resolved in DigitInitialize. A 'D'
  // attribute has one source, a '3' attribute exactly three (x, y, z).
  struct OutputSource {
    int columnIndex{-1};  // < 0 means "use constant"
    double constant{0.0};
    bool relativeToHit{false};
  };
  struct OutputTarget {
    GateVDigiAttribute *attribute{};
    bool isVector{false};
    OutputSource scalar;
    OutputSource components[3];  // x, y, z; only when isVector
  };
  // The attributes filled straight from the model columns.
  std::vector<OutputTarget> fOutputTargets;
  // The attributes computed from one of the above instead. Kept in their own
  // list so the per-photon loop never has to test for them.
  std::vector<GateVDigiAttribute *> fWorldFromModuleAttributes;

  struct FromHitTarget {
    GateVDigiAttribute *attribute{};
    char type{};  // 'U' or 'I'
    // index into threadLocalT::fromHitInts, for an 'I' attribute
    int intSlot{-1};
  };
  std::vector<FromHitTarget> fFromHitTargets;

  // Index into fOutputTargets of the module-local position the world-frame
  // outputs are computed from; -1 when nothing is derived.
  int fModuleLocalTargetIndex{-1};

  // The attribute a "world_from_module" output is derived from. Kept as a
  // constant so the C++ and the Python validation cannot drift apart.
  static constexpr const char *fModuleLocalAttributeName =
      "PostPositionLocalModule";

  GateVDigiAttribute *fOutputSourceHitIndexAttribute{};

  struct threadLocalT {
    double *edep{};
    G4ThreeVector *pos{};
    double *time{};
    // only tracked when needed; carries the navigation history to invert the
    // module-local transform, and the module identity a "from_hit" output copies
    GateUniqueVolumeID::Pointer *volumeID{};
    // one slot per "from_hit" attribute of type 'I', sized once in
    // DigitInitialize so the iterator's pointers stay valid
    std::vector<int *> fromHitInts;
    // monotonic count of hits processed so far on this thread, across the
    // whole run (not reset per event); used as SourceHitIndex so that hits
    // from different events never alias onto the same index.
    long nHitsProcessed{0};
  };
  G4Cache<threadLocalT> fThreadLocalData;
};

#endif // GateDigitizerOpticalGenerativeActor_h
