/* --------------------------------------------------
   Copyright (C): OpenGATE Collaboration
   This software is distributed under the terms
   of the GNU Lesser General  Public Licence (LGPL)
   See LICENSE.md for further details
   -------------------------------------------------- */

#ifndef GateDigitizerOpticalGenerativeActor_h
#define GateDigitizerOpticalGenerativeActor_h

#include "../GateUniqueVolumeID.h"
#include "GateVDigitizerWithOutputActor.h"
#include <G4Cache.hh>
#include <atomic>
#include <mutex>
#include <pybind11/functional.h>
#include <pybind11/stl.h>

namespace py = pybind11;

/* For every energy-deposition step, the actor samples N from a Poisson distribution
   (N = Poisson(edep *scintillation_yield)) and calls a generative model once per hit with the
   batch size being N. The model generates N synthetic particles (e.g. optical photons) records
   in one call.
   
   The precise quantities that are generated can be declared in the bundle manifest which caries
   additional information about the generative model used.
*/


class GateDigitizerOpticalGenerativeActor : public GateVDigitizerWithOutputActor {

public:
  // Callback called once per hit, or once per batch when pooling. Reads the
  // calling thread's generatorIO and fills its columns, one vector per model
  // column, all of the same length.
  using GeneratorType =
      std::function<void(GateDigitizerOpticalGenerativeActor *)>;

  explicit GateDigitizerOpticalGenerativeActor(py::dict &user_info);

  ~GateDigitizerOpticalGenerativeActor() override;

  void InitializeUserInfo(py::dict &user_info) override;

  void StartSimulationAction() override;

  void EndOfEventAction(const G4Event *event) override;

  // flushes what is left in the pool before the base class writes the run out
  void EndOfRunAction(const G4Run *run) override;

  void SetGeneratorFunction(GeneratorType &f);

  // scintillation yield in photons/MeV; N ~ Poisson(edep * yield)
  double fScintillationYield;

  // What the generator reads and writes. One set per worker thread, since in
  // MT every thread calls the generator for its own hits.
  struct generatorIO {
    // input, set once per hit before calling fGenerator
    double x{}, y{}, z{};
    double time{};
    long n{};  // number of photons generated by this hit

    // pooled input, used instead of the scalars above when fPooling is set.
    // one entry per photon, so a single call covers photons from several hits
    // and, since the pool is not flushed per event, from several events.
    // all four have the same length.
    std::vector<double> xs, ys, zs, times;

    // output: one vector per model column, in the order the declared outputs
    // list them (constant slots excluded). All columns share one length,
    // which may be smaller than n
    std::vector<std::vector<double>> columns;
  };
  G4Cache<generatorIO> fGeneratorIO;

  // the calling thread's set, which is what the python side reads and writes
  generatorIO &GetGeneratorIO() { return fGeneratorIO.Get(); }

protected:
  void DigitInitialize(
      const std::vector<std::string> &attributes_not_in_filler) override;

  GeneratorType fGenerator;

  // The declared output schema, one entry per slot, filled from user_info.
  // A slot is either a model column (fOutputColumnIndices >= 0, indexing into
  // fOutputColumns) or a constant (index < 0, value in fOutputConstants).
  std::vector<std::string> fOutputAttributeNames;
  std::vector<std::string> fOutputComponents;  // "x", "y", "z" or "" (scalar)
  std::vector<int> fOutputColumnIndices;
  std::vector<double> fOutputConstants;
  // 1 = value is a delay relative to the hit's GlobalTime, 0 = absolute
  std::vector<int> fOutputRelativeToHit;
  // 0=ordinary slot, 1=module-local position transformed back into the world
  // frame, 2=copied from the hit that produced the photon
  static constexpr int fDerivedNone = 0;
  static constexpr int fDerivedWorldFromModule = 1;
  static constexpr int fDerivedFromHit = 2;
  std::vector<int> fOutputDerived;

  // number of columns the generator must return (slots that are not constants)
  int fNumberOfModelColumns{0};

  // whether the input's PreStepUniqueVolumeID has to be tracked: to invert the
  // module-local transform, to copy it onto every photon, or both
  bool fNeedsVolumeID{false};

  // the attributes declared "from_hit", in the order they were declared
  std::vector<std::string> fFromHitAttributeNames;

  // One target per distinct attribute, resolved in DigitInitialize. A 'D'
  // attribute has one source, a '3' attribute exactly three (x, y, z).
  struct OutputSource {
    int columnIndex{-1};  // < 0 means "use constant"
    double constant{0.0};
    bool relativeToHit{false};
  };
  struct OutputTarget {
    GateVDigiAttribute *attribute{};
    bool isVector{false};
    OutputSource scalar;
    OutputSource components[3];  // x, y, z; only when isVector
  };
  // The attributes filled straight from the model columns.
  std::vector<OutputTarget> fOutputTargets;
  // The attributes computed from one of the above instead. Kept in their own
  // list so the per-photon loop never has to test for them.
  std::vector<GateVDigiAttribute *> fWorldFromModuleAttributes;

  struct FromHitTarget {
    GateVDigiAttribute *attribute{};
    char type{};  // 'U' or 'I'
    // index into threadLocalT::fromHitInts, for an 'I' attribute
    int intSlot{-1};
  };
  std::vector<FromHitTarget> fFromHitTargets;

  // Index into fOutputTargets of the module-local position the world-frame
  // outputs are computed from; -1 when nothing is derived.
  int fModuleLocalTargetIndex{-1};

  // The attribute a "world_from_module" output is derived from. Kept as a
  // constant so the C++ and the Python validation cannot drift apart.
  static constexpr const char *fModuleLocalAttributeName =
      "PostPositionLocalModule";

  GateVDigiAttribute *fOutputSourceHitIndexAttribute{};

  // one pooled hit. the generator only gets position and time, the rest is
  // what the fill loop needs afterwards to write the photons of this hit.
  struct PooledHit {
    long nRequested{0};  // photons asked for, the pool slice is this long
    double hitTime{0.0};
    // held by value: the hit the pointer came from is gone by the time the
    // pool is flushed, which may be several events later.
    GateUniqueVolumeID::Pointer volumeID;
    const G4AffineTransform *worldFromModule{};
    std::vector<int> fromHitInts;  // one per 'I' attribute, in target order
    double sourceHitIndex{0.0};
  };

  // how many photons the actor aims to collect before calling the generator.
  // 0 means no pooling, one call per hit as before.
  long fTargetBatch{0};
  bool fPooling{false};

  // every thread numbers its hits from its own offset, so a SourceHitIndex
  // belongs to one hit
  static constexpr long fSourceHitIndexStride = 1000000000L;
  std::atomic<long> fNextThreadIndex{0};

  struct threadLocalT {
    double *edep{};
    G4ThreeVector *pos{};
    double *time{};
    // only tracked when needed; carries the navigation history to invert the
    // module-local transform, and the module identity a "from_hit" output copies
    GateUniqueVolumeID::Pointer *volumeID{};
    // one slot per "from_hit" attribute of type 'I', sized once in
    // DigitInitialize so the iterator's pointers stay valid
    std::vector<int *> fromHitInts;
    // monotonic count of hits processed so far on this thread, across the
    // whole run (not reset per event); used as SourceHitIndex so that hits
    // from different events never alias onto the same index. Offset by
    // threadIndexOffset so the indices stay distinct across threads too.
    long nHitsProcessed{0};
    // set once per thread, see fSourceHitIndexStride
    long threadIndexOffset{-1};
    // hits waiting for the next generator call, and how many photons they
    // add up to. only used when fPooling is set.
    std::vector<PooledHit> pool;
    long pooledPhotons{0};
  };
  G4Cache<threadLocalT> fThreadLocalData;

  // append one hit to the pool and call the generator once the target batch
  // size is reached.
  void PoolHit(threadLocalT &l, long nRequested, double sourceHitIndex);

  // run the generator on everything in the pool and write the photons.
  // called when the pool is full and at the end of the run for the rest.
  void FlushPool(threadLocalT &l);

  // write nRows photons of one pooled hit, reading the model columns from
  // offset onwards.
  void FillPhotons(const PooledHit &hit, long offset, long nRows);

  // checks what the generator returned against the declared schema and
  // against nAsked, and returns the row count.
  long CheckOutputColumns(long nAsked);

  // gives the calling thread its own iterator over the input collection
  void SetUpInputIterator();

  // the schema is resolved by whichever worker gets there first
  std::mutex fSchemaMutex;
  bool fSchemaResolved{false};

  // the transform of the module the hit is in, used to get from module-local
  // coordinates back to the world
  const G4AffineTransform *
  ResolveWorldFromModule(const GateUniqueVolumeID::Pointer &volumeID) const;
};

#endif // GateDigitizerOpticalGenerativeActor_h
